[tox]
minversion = 3.12
envlist = py312, flake8
isolated_build = true

[gh-actions]
python =
    3.12: py312

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
deps =
    -r{toxinidir}/requirements_dev.txt
commands =
    pytest --basetemp={envtmpdir}

[testenv:flake8]
basepython = python3.12
deps = flake8
commands = flake8 src tests
